name: rrule_generator
description: RRuleGenerator is a widget for generating recurrence rules, such as described in the iCalendar RFC
version: 0.9.1
homepage: https://www.jelter.net
repository: https://github.com/tkortekaas/rrule_generator

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: '>=0.17.0 <0.21.0'

dev_dependencies:
  flutter_lints: ^5.0.0
